/* Generated By:JavaCC: Do not edit this line. PolicyDefParserConstants.java */
package org.mxupdate.update.datamodel.policy;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface PolicyDefParserConstants_mxJPO {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DESCRIPTION = 5;
  /** RegularExpression Id. */
  int TYPE = 6;
  /** RegularExpression Id. */
  int FORMAT = 7;
  /** RegularExpression Id. */
  int STORE = 8;
  /** RegularExpression Id. */
  int DEFAULTFORMAT = 9;
  /** RegularExpression Id. */
  int DELIMITER = 10;
  /** RegularExpression Id. */
  int SEQUENCE = 11;
  /** RegularExpression Id. */
  int MAJORSEQUENCE = 12;
  /** RegularExpression Id. */
  int HIDDEN = 13;
  /** RegularExpression Id. */
  int STATE = 14;
  /** RegularExpression Id. */
  int ALLSTATE = 15;
  /** RegularExpression Id. */
  int REGISTEREDNAME = 16;
  /** RegularExpression Id. */
  int REVISION = 17;
  /** RegularExpression Id. */
  int MAJORREVISION = 18;
  /** RegularExpression Id. */
  int VERSION = 19;
  /** RegularExpression Id. */
  int PROMOTE = 20;
  /** RegularExpression Id. */
  int CHECKOUTHISTORY = 21;
  /** RegularExpression Id. */
  int REVOKE = 22;
  /** RegularExpression Id. */
  int OWNER = 23;
  /** RegularExpression Id. */
  int PUBLIC = 24;
  /** RegularExpression Id. */
  int USER = 25;
  /** RegularExpression Id. */
  int FILTER = 26;
  /** RegularExpression Id. */
  int ACTION = 27;
  /** RegularExpression Id. */
  int CHECK = 28;
  /** RegularExpression Id. */
  int OVERRIDE = 29;
  /** RegularExpression Id. */
  int INPUT = 30;
  /** RegularExpression Id. */
  int TRIGGER = 31;
  /** RegularExpression Id. */
  int APPROVE = 32;
  /** RegularExpression Id. */
  int IGNORE = 33;
  /** RegularExpression Id. */
  int REJECT = 34;
  /** RegularExpression Id. */
  int BRANCH = 35;
  /** RegularExpression Id. */
  int SIGNATURE = 36;
  /** RegularExpression Id. */
  int ROUTE = 37;
  /** RegularExpression Id. */
  int BOOLEAN_TRUE = 42;
  /** RegularExpression Id. */
  int BOOLEAN_FALSE = 43;
  /** RegularExpression Id. */
  int BOOLEAN_TRUESTR = 44;
  /** RegularExpression Id. */
  int BOOLEAN_FALSESTR = 45;
  /** RegularExpression Id. */
  int LS_CURLY_BRACKET_OPEN = 50;
  /** RegularExpression Id. */
  int LS_CURLY_BRACKET_CLOSE = 51;
  /** RegularExpression Id. */
  int LS_STRING = 52;
  /** RegularExpression Id. */
  int LS_SINGLE_STRING = 53;
  /** RegularExpression Id. */
  int LS_APOSTROPHE = 54;
  /** RegularExpression Id. */
  int LS_CHAR = 55;
  /** RegularExpression Id. */
  int SL_STRING = 60;
  /** RegularExpression Id. */
  int SL_SINGLE_STRING = 61;
  /** RegularExpression Id. */
  int SL_APOSTROPHE = 62;
  /** RegularExpression Id. */
  int SL_CHAR = 63;
  /** RegularExpression Id. */
  int S_STRING = 68;
  /** RegularExpression Id. */
  int S_SINGLE_STRING = 69;
  /** RegularExpression Id. */
  int S_APOSTROPHE = 70;
  /** RegularExpression Id. */
  int S_CHAR = 71;
  /** RegularExpression Id. */
  int LALL_CURLY_BRACKET_OPEN = 76;
  /** RegularExpression Id. */
  int LALL_ALL = 77;
  /** RegularExpression Id. */
  int L_CURLY_BRACKET_OPEN = 82;
  /** RegularExpression Id. */
  int L_CURLY_BRACKET_CLOSE = 87;
  /** RegularExpression Id. */
  int L_STRING = 88;
  /** RegularExpression Id. */
  int L_SINGLE_STRING = 89;
  /** RegularExpression Id. */
  int L_APOSTROPHE = 90;
  /** RegularExpression Id. */
  int L_CHAR = 91;
  /** RegularExpression Id. */
  int L2_CURLY_BRACKET_OPEN = 92;
  /** RegularExpression Id. */
  int L3_BRACE_STRING = 93;
  /** RegularExpression Id. */
  int L3_CHAR = 94;
  /** RegularExpression Id. */
  int L4_CURLY_BRACKET_CLOSE = 95;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int B_EXPECTED = 1;
  /** Lexical state. */
  int LS_EXPECTED = 2;
  /** Lexical state. */
  int SL_EXPECTED = 3;
  /** Lexical state. */
  int S_EXPECTED = 4;
  /** Lexical state. */
  int LALL_EXPECTED = 5;
  /** Lexical state. */
  int L_EXPECTED = 6;
  /** Lexical state. */
  int L2_EXPECTED = 7;
  /** Lexical state. */
  int L3_EXPECTED = 8;
  /** Lexical state. */
  int L4_EXPECTED = 9;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"description\"",
    "\"type\"",
    "\"format\"",
    "\"store\"",
    "\"defaultformat\"",
    "\"delimiter\"",
    "\"sequence\"",
    "\"majorsequence\"",
    "\"hidden\"",
    "\"state\"",
    "\"allstate\"",
    "\"registeredName\"",
    "\"revision\"",
    "\"majorrevision\"",
    "\"version\"",
    "\"promote\"",
    "\"checkouthistory\"",
    "\"revoke\"",
    "\"owner\"",
    "\"public\"",
    "\"user\"",
    "\"filter\"",
    "\"action\"",
    "\"check\"",
    "\"override\"",
    "\"input\"",
    "\"trigger\"",
    "\"approve\"",
    "\"ignore\"",
    "\"reject\"",
    "\"branch\"",
    "\"signature\"",
    "\"route\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<BOOLEAN_TRUE>",
    "<BOOLEAN_FALSE>",
    "<BOOLEAN_TRUESTR>",
    "<BOOLEAN_FALSESTR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "<LS_STRING>",
    "<LS_SINGLE_STRING>",
    "\"\\\"\"",
    "<LS_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SL_STRING>",
    "<SL_SINGLE_STRING>",
    "\"\\\"\"",
    "<SL_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<S_STRING>",
    "<S_SINGLE_STRING>",
    "\"\\\"\"",
    "<S_CHAR>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"all\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"}\"",
    "<L_STRING>",
    "<L_SINGLE_STRING>",
    "\"\\\"\"",
    "<L_CHAR>",
    "\"{\"",
    "<L3_BRACE_STRING>",
    "<L3_CHAR>",
    "\"}\"",
    "\"{\"",
    "\"}\"",
  };

}
